name: Secret Demo Workflow

on:
 push:
  branches:
    - main
jobs:
  secret-demo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Acces secret
      run: echo "Secret is $MY_SECRET"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
